# Generated by Django 4.2.9 on 2024-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
